# Generated by Django 5.2.4 on 2025-07-11 06:28

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("nick", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("action", models.BooleanField(default=False)),
                ("command", models.CharField(blank=True, max_length=50, null=True)),
                ("host", models.TextField(blank=True, null=True)),
                ("raw", models.TextField(blank=True, null=True)),
                ("room", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "search_index",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bots.chatbot",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bots.channel",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["channel", "timestamp"],
                        name="logs_log_channel_f938fe_idx",
                    )
                ],
            },
        ),
    ]
