# Generated by Django 5.2.4 on 2025-07-11 06:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="IRC expects room name: #django", max_length=250
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "private_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Slug used for private rooms",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Password (mode +k) if the channel requires one",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                            ("BANNED", "Banned"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("fingerprint", models.CharField(blank=True, max_length=36, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ChatBot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "server",
                    models.CharField(
                        help_text="Format: irc.example.net:6697", max_length=100
                    ),
                ),
                (
                    "server_password",
                    models.CharField(
                        blank=True,
                        help_text="IRC server password - PASS command. Optional",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("server_identifier", models.CharField(max_length=164)),
                ("nick", models.CharField(max_length=64)),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Password to identify with NickServ. Optional.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        help_text="Usually a URL with information about this bot.",
                        max_length=250,
                    ),
                ),
                ("slug", models.CharField(db_index=True, max_length=50)),
                ("max_channels", models.IntegerField(default=200)),
            ],
        ),
        migrations.CreateModel(
            name="UserCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateField()),
                (
                    "counts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True),
                        blank=True,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
