# Generated by Django 5.2.4 on 2025-07-11 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0001_initial"),
        ("plugins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="plugins",
            field=models.ManyToManyField(
                through="plugins.ActivePlugin", to="plugins.plugin"
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="chatbot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bots.chatbot"
            ),
        ),
        migrations.AddField(
            model_name="usercount",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bots.channel"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channel",
            unique_together={("name", "chatbot"), ("slug", "chatbot")},
        ),
    ]
